fail_fast: true

exclude: ^docs/runtime/|.*\.(fits|fit|pha|arf|rmf)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: check-yaml
        args:
          - --unsafe
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.3
    hooks:
      - id: ruff-format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^docs/
