[tool.poetry]
name = "jaxspec"
version = "0.1.0"
description = "jaxspec is a bayesian spectral fitting library for X-ray astronomy."
authors = ["sdupourque <sdupourque@irap.omp.eu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
jax = "^0.4.18"
jaxlib = "^0.4.18"
numpy = "^1.26.1"
pandas = "^2.1.1"
astropy = "^5.3.4"
numpyro = "^0.13.2"
dm-haiku = "^0.0.10"
networkx = "^3.1"
matplotlib = "^3.8.0"
arviz = "^0.16.1"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.5.3"
mkdocs-material = "^9.4.6"
mkdocstrings = {extras = ["python"], version = "^0.23.0"}
mkdocs-jupyter = "^0.24.6"


[tool.poetry.group.test.dependencies]
chex = "^0.1.83"
mktestdocs = "^0.2.1"
coverage = "^7.3.2"
pytest-cov = "^4.1.0"
pytest = "^7.4.2"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
