[tool.poetry]
name = "jaxspec"
version = "0.1.0"
description = "jaxspec is a bayesian spectral fitting library for X-ray astronomy."
authors = ["sdupourque <sdupourque@irap.omp.eu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
jax = "^0.4.18"
jaxlib = "^0.4.18"
numpy = "^1.26.1"
pandas = "^2.1.1"
astropy = "^5.3.4"
numpyro = "^0.13.2"
dm-haiku = "^0.0.10"
networkx = "^3.1"
matplotlib = "^3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
