# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/test-and-coverage.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/test-and-coverage.yml'


permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with test
    - name: Test with pytest
      run: |
        pytest --cov jaxspec
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
